name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Standard checks
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: amoeba/standardrb-action@v1
